### ISSUE TITLE
Does not work on current stable release 2.2.0

### ISSUE THREAD

**Issue by jsroest** [zanderso/chicago#2]
Hi Todd,

Awesome talk and what a great library.

You might want to point out somewhere what the minimum required version of Flutter for this repo is. I did try the current latest stable (2.2.0), but then there were a lot of errors like:
../lib/src/scroll_bar.dart:826:29: Error: Type 'LongPressDownDetails' not found.

Switching to 2.3.0-1.0.pre solved it for me.

Regards,
Sander

**Comment by tvolkert** [comment]
Thanks for calling this out!  I added a disclaimer -- https://github.com/tvolkert/chicago#disclaimer
