### ISSUE TITLE
How to localization and change font

### ISSUE THREAD

**Issue by xyun52** [zanderso/chicago#27]
How to localization and change font

**Comment by tvolkert** [comment]
Adding a [DefaultTextStyle](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html) should allow you to change the font.

You can localize your Strings using [package:intl](https://pub.dev/packages/intl).  Unfortunately, the widgets built into Chicago (like `CalendarButton`) don't have localization built-in right now, but I'd gladly accept pull requests that added that functionality 🙂 . You'd have to create a [`GlobalChicagoLocalizations.delegate`](https://api.flutter.dev/flutter/material/MaterialApp/localizationsDelegates.html)
